version: '3.8'

services:
  backend:
    # build: ./backend
    image: alsandrecr.azurecr.io/flask-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_USER=intuit
      - MONGO_PASS=clippers
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_INITDB_NAME=tasks_db
    volumes:
      - ./backend:/app

  frontend:
    # build: ./frontend
    image: alsandrecr.azurecr.io/react-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL='http://localhost:5000'
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=intuit
      - MONGO_INITDB_ROOT_PASSWORD=clippers
      - MONGO_INITDB_DATABASE=tasks_db     
    volumes:
      - mongo_data:/data/db             
    restart: always                           
    command: ["mongod", "--bind_ip_all"]     

volumes:
  mongo_data: