name: Build and Push Docker Images to Azure ACR

on:
  push:
    branches:
      - main  # Adjust if your default branch is different
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AZURE_ACR_LOGIN_SERVER: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
      AZURE_ACR_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}
      AZURE_ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
      BACKEND_IMAGE_NAME: flask-backend  # Adjust as per your naming convention
      FRONTEND_IMAGE_NAME: react-frontend  # Adjust as per your naming convention
      IMAGE_TAG: 1.0.0-${{ github.sha }}  # Use SHA as the image tag or adjust as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure ACR
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Build Backend Image
      - name: Build backend Docker image
        run: |
          docker build -t ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f backend/Dockerfile .

      # Push Backend Image to ACR
      - name: Push backend Docker image to ACR
        run: |
          docker push ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # Build Frontend Image
      - name: Build frontend Docker image
        run: |
          docker build -t ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f frontend/Dockerfile .

      # Push Frontend Image to ACR
      - name: Push frontend Docker image to ACR
        run: |
          docker push ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
