name: Build and Push Docker Images to Azure ACR

on:
  push:
    branches:
      - main  # Adjust if your default branch is different
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: develop

    env:
      AZURE_ACR_LOGIN_SERVER: alsandrecr.azurecr.io
      AZURE_ACR_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}
      AZURE_ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
      BACKEND_IMAGE_NAME: flask-backend  
      FRONTEND_IMAGE_NAME: react-frontend  
      IMAGE_TAG: 1.0.0-${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure ACR
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Build and Push Backend Image
      - name: Build and Push backend Docker image
        run: |
          docker build -t ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f backend/Dockerfile backend/
          docker push ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:latest
          docker push ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:latest

      # Build and Push Frontend Image
      - name: Build and Push frontend Docker image
        run: |
          docker build -t ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f frontend/Dockerfile frontend/
          docker push ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
          docker push ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:latest 

      # # Build Backend Image
      # - name: Build backend Docker image
      #   run: |
      #     docker build -t ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f backend/Dockerfile backend/
      #     # Tag the backend image with :latest
      #     docker tag ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:latest

      # # Push Backend Image to ACR
      # - name: Push backend Docker images to ACR
      #   run: |
      #     docker push ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #     docker push ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE_NAME }}:latest

      # # Build Frontend Image
      # - name: Build frontend Docker image
      #   run: |
      #     docker build -t ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f frontend/Dockerfile frontend/
      #     docker tag ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
      # # Push Frontend Image to ACR
      # - name: Push frontend Docker image to ACR
      #   run: |
      #     docker push ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #     docker push ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE_NAME }}:latest